---
driver:
  name: vagrant
  network:
    - ['private_network', { ip: '192.168.0.12' }]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

platforms:
  - name: ubuntu-14.04
    driver:
      box: opscode-ubuntu-14.04
      customize:
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[railsapp::default]
    attributes:
      rvm:
        user:
          name: 'vagrant'
          password: 'vagrant'
          home: '/home/vagrant'
      railsapp:
        application: 'myfamilyweb'
        rails_env: 'production'
        deployer:
          username: 'vagrant'
        db:
          name: 'dbname'
          username: 'dbuser'
          password: 'dbuser123'
        webserver:
          name: 'myfamilyweb.local'
          document_root: '/www/deploy/myfamilyweb/releases/current/public'
          secret_key_base: '8d7d7213485b5b960f753222a5e3f2974aaa19c3c99c84b575c0d7db409dc093bbcc8c5f08ec77c1a057631b9df50d6679bd3873da7b28030ce23075d8ebc127'
