---
driver:
  name: vagrant
  network:
    - ['private_network', { ip: '192.168.0.12' }]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      customize:
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[railsapp::default]
    attributes:
      rvm:
        user:
          name: 'vagrant'
          password: 'vagrant'
      railsapp:
        server_name: 'mytestapp.local'
        application_name: '/home/vagrant/deploy'
