---
driver:
  name: vagrant
  network:
    - ['private_network', { ip: '192.168.0.12' }]

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: ubuntu-14.04
    driver:
      box: opscode-ubuntu-14.04
      customize:
        memory: 2048

suites:
  - name: default
    data_bags_path: 'test/integration/data_bags'
    run_list:
      - recipe[rubystack::rails_deploy]
    attributes:
      web_server:
        sites:
          - server_name: 'myfamilyweb.local'
            server_alias:
              - 'www.myfamilyweb.local'
            document_root: '/var/www/myfamilyweb/current/public'
            friendly_error_pages: true
      rails_apps:
        - deploy_dir: '/var/www/myfamilyweb'
          rails_env: 'production'
          database:
            adapter: 'postgresql'
            hostname: 'localhost'
            name: 'myfamilyweb'
            password: 'dbuser123'
            username: 'dbuser'
          secrets:
            secret_key_base: 'abcdefghijklmnopqrstuvwxyz0123456789'


