---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      customize:
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[railsapp::default]
    attributes:
  - name: db
    run_list:
      - recipe[railsapp::setup_database]
    attributes:
